### PR TITLE
Remove symlinks; Keep Arduino lib spec v1.5; Tell Makefile our lib is called 'src'

### PR DESCRIPTION
**Pull request by noporpoise**
Arduino Library doesn't want repos with symlinks, so we need to remove them.

We used symlinks because:
The Arduino library requires us to have our source in a directory called 'src'
in the root of the repo. However, the Arduino-Makefile looks for each library in a directory with its name.

To work around we tell ArduinoMakefile that our library oatmeal-protocol is
called 'src'.

Additional patches:
* Rename Arduino library name to oatmeal-protocol to match repo name etc.
* Add a missing release step (update docs with Arduino lib version number)

### CODE REVIEW

**Comment by ExplodingCabbage** [comment]
Hmm. The "pretend our library is named `src`" approach in the Makefile is ugly, but I don't see a nicer solution. The update we got at https://github.com/arduino/Arduino/issues/8845#issuecomment-492455684 doesn't change anything that would let us avoid the hack.

Some thoughts:
* Were these examples previously broken on Windows (where I think Git mangles symlinks in repos)? Possibly being made to strip out symlinks has done us a favour by making us fix things that were broken for Windows users.
* Perhaps we could find some other repos of libraries that have Arduino-Makefile examples (or just makefiles in their examples folder in general) as well as being in the library manager, and see how they handle it?

**Comment by noporpoise** [comment]
An alternative solution is to rename the Arduino project to match the repo name (`oatmeal-project` not `OatmealProtocol`) and move the source files to the root directory (permitted under the 1.0 library spec). `oatmeal-project` is a [permitted Arduino library name](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format). 

There are only three C++ files (`oatmeal_message.h`, `oatmeal_protocol.cpp`, `oatmeal_protocol.h`) so this wouldn't be too ugly. I've put together a PR: #9

**Comment by noporpoise** [comment]
@ExplodingCabbage following the discussion at PR #9, it sounds like this is the preferred fix. If you approve please squash merge and I'll replace the old release with this one.

**Comment by ExplodingCabbage** [comment]
LGTM.

**Pull request merged**
